import { ArrowLeft, Check, CheckCircle2, ChevronDown, Clock3, GitBranch, Send, Sparkles, Target } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useState } from 'react'
import AppHeader from '../components/AppHeader'
import BottomNav from '../components/BottomNav'
import ProgressBar from '../components/ProgressBar'
import { challenge } from '../data/mockData'

const Github = GitBranch
const Linkedin = Send

function ProofCard({ type, icon: Icon, submitted, onSubmit }) { const [open, setOpen] = useState(false); const [url, setUrl] = useState(''); const [reference, setReference] = useState(''); if (submitted) return <article className="proof-card proof-complete"><div className="proof-title"><span className="proof-type"><Icon size={19}/>{type}</span><CheckCircle2 size={20}/></div><strong>{type} proof submitted</strong><p>Your link is saved for this demo.</p></article>; return <article className="proof-card"><div className="proof-title"><span className="proof-type"><Icon size={19}/>{type}</span><button onClick={() => setOpen(!open)} aria-expanded={open}>{open ? 'Close' : 'Add proof'} <ChevronDown size={15}/></button></div>{open ? <div className="proof-form"><label>{type === 'GitHub' ? 'Repository URL' : 'Post URL'}<input value={url} onChange={e => setUrl(e.target.value)} placeholder={type === 'GitHub' ? 'github.com/you/project' : 'linkedin.com/posts/...'} /></label>{type === 'GitHub' && <label>Commit / proof reference <input value={reference} onChange={e => setReference(e.target.value)} placeholder="e.g. main · a1b2c3" /></label>}<button className="button button-primary proof-submit" onClick={() => { if (url.trim()) onSubmit() }} disabled={!url.trim()}>Submit {type} proof <Check size={17}/></button></div> : <p>Share the link when your work is ready.</p>}</article> }

export default function ChallengeDay() { const [github, setGithub] = useState(false); const [linkedin, setLinkedin] = useState(false); const completed = github && linkedin; return <main className="app-shell"><AppHeader /><div className="challenge-content"><Link to="/dashboard" className="back-link"><ArrowLeft size={18}/> Back to dashboard</Link>{completed ? <section className="completion"><div className="completion-mark">✦</div><p className="section-kicker">DAY 12 COMPLETE</p><h1>You shipped it. <br/>Keep the rhythm.</h1><p>Your proof is in. This is how a public portfolio gets built — one finished day at a time.</p><div className="completion-stats"><strong>12 / 60</strong><span>+100 XP</span><span>🔥 12-day streak</span></div><Link className="button button-primary full-button" to="/dashboard">Back to your dashboard</Link></section> : <><section className="challenge-hero"><div className="challenge-meta"><span className="pill">DAY 12 OF 60</span><span><Clock3 size={15}/>{challenge.duration}</span></div><p className="section-kicker">{challenge.category}</p><h1>{challenge.title}</h1><span className="difficulty"><Target size={15}/>{challenge.difficulty}</span></section><ProgressBar value={12}/><section className="why-card"><span className="why-icon"><Sparkles size={19}/></span><div><p className="section-kicker">WHY THIS MATTERS</p><p>{challenge.reason}</p></div></section><section className="challenge-section"><p className="section-kicker">YOUR BRIEF</p><h2>What you’re building</h2><p>{challenge.brief}</p></section><section className="challenge-section"><p className="section-kicker">REQUIREMENTS</p><h2>Keep it focused</h2><ul className="requirement-list">{challenge.requirements.map((item, i) => <li key={item}><span>{String(i + 1).padStart(2, '0')}</span>{item}</li>)}</ul></section><section className="done-section"><p className="section-kicker">DEFINITION OF DONE</p><h2>You can submit when…</h2><p>Use this as your confident finish line.</p><div>{challenge.done.map(item => <label className="done-item" key={item}><input type="checkbox"/><span className="fake-checkbox"><Check size={13}/></span>{item}</label>)}</div></section><section className="proof-section-app"><div><p className="section-kicker">SHOW YOUR WORK</p><h2>Submit your proof</h2><p>We’ll save your links in this demo. We don’t verify them automatically.</p></div><ProofCard type="GitHub" icon={Github} submitted={github} onSubmit={() => setGithub(true)}/><ProofCard type="LinkedIn" icon={Linkedin} submitted={linkedin} onSubmit={() => setLinkedin(true)}/></section></>}</div><BottomNav /></main> }
