import { ArrowRight, Check, ChevronDown, GitBranch, Send, Sparkles } from 'lucide-react'
import { Link } from 'react-router-dom'
import Brand from '../components/Brand'
import { journey } from '../data/mockData'

const Github = GitBranch
const Linkedin = Send

const Step = ({ number, title, children }) => <article className="method-step"><span className="step-number">0{number}</span><div><h3>{title}</h3><p>{children}</p></div></article>
export default function Landing() { return <main className="site-shell landing">
  <header className="landing-header"><Brand /><Link className="sign-in" to="/dashboard">Sign in <ArrowRight size={15}/></Link></header>
  <section className="hero"><div className="eyebrow"><span className="live-dot" /> The 60-Day Challenge</div><h1>Code consistently.<br/><em>Build in public.</em><br/>Get noticed.</h1><p className="hero-copy">A focused daily challenge that turns your effort into real skills, visible work and a portfolio you’re proud to share.</p><div className="hero-actions"><Link className="button button-primary" to="/dashboard">Start your 60 days <ArrowRight size={18}/></Link><a className="button button-quiet" href="#how-it-works">See how it works <ChevronDown size={17}/></a></div><div className="hero-meter" aria-label="A 60 day journey"><div><strong>01</strong><span>Start small</span></div><i/><div><strong>30</strong><span>Build a habit</span></div><i/><div><strong>60</strong><span>Show your work</span></div></div></section>
  <section className="intro-section" id="how-it-works"><p className="section-kicker">A challenge, not another course</p><h2>One meaningful build. Every day.</h2><p>You choose a track, receive a focused task and share what you made. No pressure to be perfect — just a clear next step each day.</p><div className="method-list"><Step number="1" title="Learn daily">Practical prompts across software, data and AI — designed to fit around college.</Step><Step number="2" title="Build & prove it">Push your work to GitHub and share your progress. Your consistency becomes visible.</Step><Step number="3" title="Grow together">Keep your momentum with a community that is building alongside you.</Step></div></section>
  <section className="journey-section"><p className="section-kicker">A little further, every day</p><h2>Your 60 days, made visible.</h2><div className="journey-line">{journey.map((item, i) => <div className="journey-item" key={item.name}><span className="journey-dot">{i + 1}</span><div><small>{item.range}</small><h3>{item.name}</h3><p>{item.note}</p></div></div>)}</div></section>
  <section className="proof-section"><div className="proof-icon"><Sparkles size={23}/></div><p className="section-kicker">Progress people can see</p><h2>Don’t just say you’re learning. Show it.</h2><p>Each completed day adds a real piece of proof to your public body of work.</p><div className="proof-mini"><span><Github size={18}/> Your project</span><Check size={17}/><span><Linkedin size={18}/> Your progress</span></div></section>
  <section className="community-section"><div className="quote-mark">“</div><h2>Build in public.<br/>Grow together.</h2><p>ABTalks is a place to keep showing up — with other students who are doing the same.</p><Link className="text-link" to="/dashboard">Explore the challenge <ArrowRight size={17}/></Link></section>
  <section className="final-cta"><p className="section-kicker">Your first day starts here</p><h2>Make today’s work count.</h2><p>You don’t need 60 days of confidence. You only need enough for day one.</p><Link className="button button-primary full-button" to="/dashboard">Start the 60-Day Challenge <ArrowRight size={18}/></Link></section><footer><Brand light/><span>Build in public. Grow together.</span></footer></main> }
